### ISSUE TITLE
beforeConnecting hook for merging workflows

### ISSUE THREAD

**Issue by connors511** [ksassnowski/venture#13]
It's possible to conditionally add jobs and workflows in the `definition` method, however, I'd like to have all my jobs added and instead early return from them before they do any work.
In order to do so I've added a `$shouldSkip` property to my jobs and workflows.

It works fine for jobs, but I'm having a little difficulty when merging workflows.

Consider this example;
```php
Workflow::define('My workflow')
    ->addJob(new MyJob())
    ->addJob((new MyOtherJob())->skip($myCondition), [
        MyJob::class,
    ])
    ->addWorkflow((new MyConditionalWorkflow())->skip($myCondition), [
        MyOtherJob::class,
    ]);
```

`MyOtherJob` is all good, but `MyConditionalWorkflow` currently needs a defintion like;
```php
Workflow::define('My conditional workflow')
    ->addJob(
        (new MyNestedJob())->skip($this->shouldSkip)
    )
```
This gets kinda cumbersome very quickly when you have a few jobs in the nested workflow.

`WorkflowDefinition::addWorkflow` could be modified with the following hook;
```php
        $definition = $workflow->definition();

        if (method_exists($workflow, 'beforeConnecting')) {
            $workflow->beforeConnecting($definition->jobs);
        }
```
-- or just call it regardless, if a no-op method was added to `AbstractWorkflow` like `beforeCreate` currently is.

What's your thoughts?
Open to a PR with tests for this, or for another implementation?

---
For reference, my `skip` is basically just the following and similar for Jobs
```php
abstract class AbstractWorkflow extends \Sassnowski\Venture\AbstractWorkflow
{
    protected bool $shouldSkip = false;

    public function skip(bool $shouldSkip = true)
    {
        return tap($this, fn () => $this->shouldSkip = $shouldSkip);
    }
}
```

**Comment by viezel** [comment]
I vote for a PR for this. I need this for a project as well.

**Comment by ksassnowski** [comment]
I am skeptical of this. At least for the example you've provided, it seems like a very convoluted way of implementing an if-statement. I'm generally against syntax for its own sake. The main benefit I see with simply using an if-statement  is that it becomes very easy to unit test using the included `hasJob` method.

`beforeConnecting` is also incredibly specific and leaks a lot of the internal behavior into user land.

Maybe you could provide other example to show how this would be useful, but as it stands I'm against adding this hook.

**Comment by connors511** [comment]
I'm using Workflows to break down processes into smaller reusable tasks. These processes are then going to be visualised for clients, so they can track the progress.

To make it easier for them to understand, and not constantly ask questions why a certain workflow or part of the process is missing, I'd like to add all jobs/workflows to the process and simply skip the processing of said jobs instead of excluding them.

Having a hook to modify jobs within a workflow would make it much easier to implement such behaviour by mass-updating the workflows jobs.

**Comment by ksassnowski** [comment]
I guess that makes sense. Give me about a day or so to see if I can come up with a different idea. If not, I'm ok with adding this sort of hook.

**Comment by ksassnowski** [comment]
Slightly unrelated. If you're rendering the workflow in the UI, check out the `asAdjacencyList()` method that was added to the `Workflow` model in v 2.0.0. Makes it really easy to render the workflow as a graph. It's what I'm using in the upcoming Venture dashboard.

**Comment by connors511** [comment]
Cool, will check it out. Related to that, is the dashboard going to be part of the Venture package or what's your plan with it :) ?

**Comment by ksassnowski** [comment]
Can you check out #16 to see if this would solve your problem?

Re Dashboard: I'm currently developing it as a standalone package but I'm seriously considering including it the main repo like Horizon does.

**Comment by connors511** [comment]
@ksassnowski it seems it would. At the very least it'd be a great starting off point. Great work.

**Comment by ksassnowski** [comment]
Cool. I've merged the PR into master. This will be part of the 2.1.0 release. I'd like to merge #21 before the release, however. I will close this ticket for now. Feel free to reopen if there is anything else to discuss.
