### ISSUE TITLE
PHP 8 required

### ISSUE THREAD

**Issue by Barmunksu** [ksassnowski/venture#26]
> This version of Venture requires PHP 8. This is because in order to provide a nice API, both internally as well �externally, named arguments are heavily used.

<img width="924" alt="Снимок экрана 2021-03-02 в 11 15 51" src="https://user-images.githubusercontent.com/4123671/109618727-f0a2e080-7b48-11eb-904c-04cd24064017.png">

[nice API](https://blog.remirepo.net/post/2020/09/21/PHP-extensions-status-with-upcoming-PHP-8.0) 
[heavily used](https://github.com/Imagick/imagick/issues/358)

**Comment by ksassnowski** [comment]
Not sure what you're trying to say with this?
