### ISSUE TITLE
Add support for user task

### ISSUE THREAD

**Issue by viezel** [ksassnowski/venture#32]
Sometimes workflows have users involved to perform an action before the workflow step is complete and the overall workflow can continue. An example would be a user that needs to review and approve a blog post before it gets published.
It would be beneficial to see support for user tasks within this package. 

A user task can be completed in e.g. a controller and the application should be able to update a specific workflow step to complete or cancelled. 

I believe we would need:

- Jobs that do not automatically completes when run - but instead is in `progress`
- workflow API to complete a step

**Comment by viezel** [comment]
I suggest to still keep the following code intact 

```php
Workflow::define('My Workflow')
    ->addJob(new MyJob())
    ->then(new SendNotification());
```

but instead, let it be the job that has the implementation

```php
class MyJob implements ShouldQueue
{
    use WorkflowStep;
    use WorkflowUserTask;
}
```

**Comment by ksassnowski** [comment]
So this would be akin to a something like a `manual` task that some CI servers support? I like the idea but I'm not sure how hard it would be to implement. If I understand correctly, this type of job wouldn't really do anything by itself but serve as some kind of "pause" inside the workflow which then has to be manually completed, right?

**Comment by viezel** [comment]
correct. It would be manual. 

First thing that comes to mind, is to change the `WorkflowEventSubscriber` so it does not automatically complete. 


```diff
public function handleJobProcessed(JobProcessed $event): void
{
    if ($event->job->isReleased()) {
        return;
    }
    
    $jobInstance = $this->getJobInstance($event->job);

    if ($this->isWorkflowStep($jobInstance)) {
+       if($this->hasUserTask($jobInstance) {
+          return;
+       }
        optional($jobInstance->workflow())->onStepFinished($jobInstance);
    }

+   private function hasUserTask($job): bool
+   {
+       $uses = class_uses_recursive($job);
+   
+       return in_array(WorkflowUserTask::class, $uses);
+   }

}
```

Next we would need to be able to manually flag the job as complete (given a certain business logic)

```php
class ApproveController
{
    public function approve($jobId)
    {
        Workflow::job($jobId)->complete();
    }
}
```

**Comment by ksassnowski** [comment]
Yeah, it might actually be a lot easier than I initially thought. I can try to have a look at this soon. Or let me know if you want to take a crack at this and submit a PR so we don't both work on the same thing

**Comment by viezel** [comment]
ive created a PR for test. Let me know what you think.

**Comment by rycks** [comment]
Hello,
i need that sort of job : one step of my business workflow is "manager validation" ..

Thanks

**Comment by ksassnowski** [comment]
This is now possible in v4 using [gated jobs](https://laravel-venture.com/usage/configuring-workflows.html#gated-jobs)

**Comment by viezel** [comment]
Fantastic!!
