### ISSUE TITLE
Sequential Execution (Job Chaining)

### ISSUE THREAD

**Issue by ellisonpatterson** [ksassnowski/venture#34]
Would it be possible to specify jobs/workflows for execution sequentially?

**Comment by ksassnowski** [comment]
Not sure if I understand your question correctly, but this is already possible. If you want a specific job to run after another job (or jobs) has finished, you should add that job as a dependency.

Say you have two jobs, `JobA` and `JobB`. If `JobB` should only run after `JobA` has finished successfully, you would declare `JobA` as a dependency of `JobB` in your workflow definition.

```php
class MyWorkflow extends AbstractWorkflow
{
    public function definition(): WorkflowDefinition
    {
        return Workflow::define('My Workflow')
            ->addJob(new JobA())
            // Declare `JobA` as a dependency of `JobB`
            ->addJob(new JobB(), [JobA::class]);
    }
}
```

See [this page](https://laravel-venture.netlify.app/usage/configuring-workflows.html#adding-jobs-to-a-workflow) of the documentation for more information about this.

Feel free to reopen this issue if I misunderstood your question.

**Comment by oliverbj** [comment]
Reviving this question again - sorry if this is not allowed.

I have a workflow, where everything must run sequentially. These are my jobs:

```php
GetPageCount::class,
CreateDocumentPages::class,
CountDocumentTokens::class,
ClassifyDocumentPages::class,
ImagizeDocumentPages::class,
ExtractSchemaFromDocument::class
```

This is a pure sequential workflow, and I used to use Laravel's batching feature to ensure that one job is finished before the next is started.

Not quite sure how this looks with Venture? Would I need to state the dependices for each of the jobs?

```php
//...
    ->addJob(new CreateDocumentPages($document), [GetPageCount::class], 'Page Count Retrieved')
    ->addJob(new CountDocumentTokens($document), [GetPageCount::class, CreateDocumentPages::class], 'Document Pages Created')
    ->addJob(new ClassifyDocumentPages($document), [GetPageCount::class, CreateDocumentPages::class, CountDocumentTokens::class], 'Document Tokens Counted')
    ->addJob(new ImagizeDocumentPages($document), [GetPageCount::class, CreateDocumentPages::class, CountDocumentTokens::class, ClassifyDocumentPages::class], 'Document Pages Classified')
    ->addJob(new ExtractSchemaFromDocument($document), [GetPageCount::class, CreateDocumentPages::class, CountDocumentTokens::class, ClassifyDocumentPages::class, ImagizeDocumentPages::class], 'Document Pages Imagized');
```
