### ISSUE TITLE
workflowDefinition hasJob dont work if passing only class name

### ISSUE THREAD

**Issue by tiagofrancafernandes** [ksassnowski/venture#35]
My code
```php
$workflowDefinition = (new AccountSignupWorkflow($validInputs))->definition();
$actual = $workflowDefinition->hasJob(\App\Jobs\AccountSignup\CreateZendeskAccountJob::class);
$this->assertTrue($actual);// works
```

```php
use App\Jobs\AccountSignup\CreateZendeskAccountJob;
$workflowDefinition = (new AccountSignupWorkflow($validInputs))->definition();
$actual = $workflowDefinition->hasJob(CreateZendeskAccountJob::class);
$this->assertTrue($actual);// dont works
```

Thats hapens because in instance of `WorkflowDefinition` my job is result of `CreateZendeskAccountJob::class`:
`App\Jobs\AccountSignup\CreateZendeskAccountJob`.

I know that beacuse I create a method `allJobs()` only to return all jobs. Like above:

```php
    //vendor/sassnowski/venture/src/WorkflowDefinition.php

    public function allJobs()
    {
        return $this->jobs;
    }
```

To work only using class name, need implements some like:

```php
$class = CreateZendeskAccountJob::class;
substr(strrchr($class, "\\"), 1)
```

**Comment by ksassnowski** [comment]
Can you check if this problem still occurs on the `3.1.2` release?

**Comment by tiagofrancafernandes** [comment]
> Can you check if this problem still occurs on the `3.1.2` release?

I will retry and come back here to say

Thank you for return

**Comment by tiagofrancafernandes** [comment]
Yes. Solved. Thank you
