### ISSUE TITLE
Share informations between jobs

### ISSUE THREAD

**Issue by homeoftheunits** [ksassnowski/venture#5]
Hey there,

is it possible to give data from one job to antother?

For example, the first job creates an job in an service, and an second job make something with the returned data

Cheers
Ralf

**Comment by ksassnowski** [comment]
Hi!

It's not possible to pass data between jobs.

If a job relies on some data created by another job, this data should be persisted somewhere (database, cache, filesystem...) and then retrieved in the second job.
