### ISSUE TITLE
Use in a non-Laravel php app or Symfony?

### ISSUE THREAD

**Issue by ttk** [ksassnowski/venture#60]
I am curious to know if it's possible to use this library/component outside of a Laravel app? Is there any other similar library for Symfony that you know of?

**Comment by stevebauman** [comment]
Hi there @ttk,

You cannot use Venture outside of Laravel, as it depends on its core features (queuing, event system, eloquent, etc.).

There is the core Symfony Workflow package that might be able to get you started:

https://symfony.com/doc/current/components/workflow.html

**Comment by ttk** [comment]
@stevebauman Thanks for the info.  I reviewed the Workflow Symfony component, but unfortunately it doesn't seem like it can handle job dependencies in the same way that Venture can (at least not without a lot of extra coding).
