### ISSUE TITLE
Define method expecting two parameters, only 1 available

### ISSUE THREAD

**Issue by thomas-grabarczyk** [ksassnowski/venture#63]
Followed documentation, it looks like the within public definition function, the returning Workflow (facade) only accepts a string (workflow name) yet the underlying class needs two parameters

Sassnowski\Venture\Manager\WorkflowManager::define(): Argument #1 ($workflow) must be of type Sassnowski\Venture\AbstractWorkflow, string given

![image](https://user-images.githubusercontent.com/99020651/205141556-c73e50e6-036b-4cc2-b389-eb4983230bea.png)

![image](https://user-images.githubusercontent.com/99020651/205141603-1740830f-f720-47cd-9a65-6e527e11cb81.png)

**Comment by ksassnowski** [comment]
Hey, you should be using `$this->define` instead of `Workflow::define`. Can you link me to the place in the docs where you found this? I must’ve forgotten to update it.

**Comment by thomas-grabarczyk** [comment]
Hey, thanks for the quick reply, The site I found you on must have had a link to the old docs page - Updated to the latest version, and checked out up-to-date docs - all worked like a breeze! 

Many thanks for the great work

**Comment by danielthomascarr** [comment]
Hey, had the same issue the link to the docs is https://laravel-venture.netlify.app/usage/configuring-workflows.html#creating-a-workflow-definition. Thanks
