### ISSUE TITLE
bootPlugins not work

### ISSUE THREAD

**Issue by wit3** [ksassnowski/venture#71]
Hi,

If i try to register a plugin (EntityAwareWorkflows) in my boot method in AppServiceProvider the plugin it's not registered

Only if i call `Venture::bootPlugins()` after it's correctly registered and work.

If i try to investigate in your test file, i notice that you call bootPlugins after registerPlugin

https://github.com/ksassnowski/venture/blob/46284524fbb113b579fe1a906987a6bcea1d675a/tests/EntityAwareWorkflowsPluginTest.php#L33

Anyone has notice this bug?

**Comment by ksassnowski** [comment]
Sorry, this is actually a mistake in the documentation. You need to call `Venture::registerPlugin` inside your service provider's `register` method, not inside the `boot` method. 

For context: the `Venture::bootPlugins` method gets called by Venture itself inside `VentureServiceProvider::boot`. So when you register your plugin in the `boot` method, the `bootPlugins` method has already been called and so your plugin doesn't get picked up. I'll fix this in the docs.

**Comment by Wit3** [comment]
Thanks for claryfing the mistake in documentation.
all work as expectedly now 👍
