### ISSUE TITLE
Unserialize exception in workflow callback (then/catch)

### ISSUE THREAD

**Issue by wit3** [ksassnowski/venture#75]
https://github.com/ksassnowski/venture/blob/bdeabdb5e1adeddb006681d22d3e018dba1da078/src/Models/Workflow.php#L246

if my job in workflow, fails and in the `define` method i've defined the catch method.
this error thrown 
```
ErrorException
unserialize(): Error at offset 157 of 709 bytes
```

my workflow:
```
.
.
.
->catch(function ($workflow, WorkflowableJob $step, Throwable $exception) {
                \event(new \App\Events\MyCustomWorkflowFailed($workflow, $step->getStepId(), $exception, $this->user));
                $workflow->cancel();
            })
```

Has anyone encountered this problem?

edit: if i try to remove event dispatch, all works

**Comment by stevebauman** [comment]
Hi @wit3,

You cannot use “$this” in closures that are serialized. The reference will be broken and it cannot be retrieved when be unserialized.

You can instead make a new variable outside of the closure equal to `$this->user`, then `use` it in the closure.

**Comment by wit3** [comment]
You r right dude 😖 thanks for clarifying

**Comment by stevebauman** [comment]
No problem @wit3! Happy to help.
