### ISSUE TITLE
Is it possible to use with the SQS driver

### ISSUE THREAD

**Issue by riabiy** [ksassnowski/venture#79]
I assume no, yet decided to ask, since haven't found any info. I understand it uses db tables, but...IDK, asked just in case :) 

Simple yes, possible/no, it's not possible to use with Amazon SQS is sufficient for me. 
Thank you :)

**Comment by ksassnowski** [comment]
While I haven't used SQS personally yet, I don't see why it wouldn't work. SQS would just be the actual queue you're using. The database tables that Venture uses are independent of your queue driver. Laravel still fires the same queue events no matter which queue driver you're using.
