### ISSUE TITLE
Collection passed as parameter to job is saved in job column to DB

### ISSUE THREAD

**Issue by jkalousek** [ksassnowski/venture#85]
I recently started using jobs in one of my Laravel project but quickly run into problems with complexity and need for dependencies. Today I found Venture and gave it a try. 
Basically I'm I need periodically get data from one DB to another.
I'm getting data, chunking them into 500 rows chunks and passing said chunk to be processed by job. Than I need to wait until processing of all the data is done and run other Job on newly updated data. First time I tried to run this scenario with venture (previously run using Jobs and chain) I got
`PDOException::("SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'job' at row 1")`
and realized that venture is saving the entire model into database. I changed job column into LONG TEXT and this time everything processed without problem, but after just one run the `workflow_jobs` table is 150 KiB. Is there anything that can be done, because basically data are stored in DB twice and the jobs table will linearly grow. Maybe solution could be an option to remove data from column `job` for non failed rows?

**Comment by stevebauman** [comment]
Hi @jkalousek,

Can you post your job code?

**Comment by jkalousek** [comment]
Main workflow is:
```
public function definition(): WorkflowDefinition
    {
        return $this->define('Materials Update')
        ->addWorkflow(new QueryMaterials)
        ->addJob(new UpdateMaterialsPPU,
        [
            QueryMaterials::class
        ])
        ->addJob(new UpdateMaterialsPPUO,
        [
            UpdateMaterialsPPU::class
        ])
        ->addJob(new UpdateMaterialsPO,
        [
            UpdateMaterialsPPUO::class
        ])
        ->addJob(function () {
            Artisan::call('scout:flush', ['model' => 'App\Models\Material']);
            Artisan::call('scout:import', ['model' => 'App\Models\Material']);
        }, id: 'update-material-search', dependencies: [
            UpdateMaterialsPO::class
        ]);
    }
```

The Nested workflows that is querying and chunking results (QueryMaterials)

```
public function definition(): WorkflowDefinition
    {
        $query = DB::connection(...);


        $workflow = $this->define('Query Materials');
        $cnt = 0;

        $query->orderBy('...', 'DESC')
        ->chunk(500, function (Collection $MatChunk) use (&$workflow, &$cnt) {
            $workflow->addJob(new UpdateMaterials($MatChunk),
                id: 'UpdateMaterials-' . $cnt
            );
            $cnt++;
        });

        return $workflow;
    }
```

The `UpdateMaterials ` Job is just looping through chunk, checking, modifying and storing results. Other functions like UpdateMaterialsPPU etc. are just runing additional operations and calculations.

**Comment by jkalousek** [comment]
The data that are stored into Job column looks like:

`SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'job' at row 1 (Connection: mysql, SQL: insert into `workflow_jobs` (`job`, `name`, `uuid`, `edges`, `gated`, `workflow_id`) values (O:30:"App\Jobs\UpdateMaterials":6:{s:11:"\*\MatChunk";O:29:"Illuminate\Support\Collection":2:{s:8:"\*\items";a:234:{i:0;O:8:"stdClass":10:{s:2:"ID";i:328;s:7:"SkupZbo";s:3:"113";s:6:"RegCis";s:10:"1.C140.006";s:6:"N...` basically storing whole serialized? collection.

**Comment by stevebauman** [comment]
@jkalousek I'm mainly looking to see if you've included the `SerializesModels` trait onto your `UpdateMaterials` job. If the job does not have this trait, then the entire Eloquent collection of all of your models is serialized, which will definitely exceed the size of the job column.

The `SerializesModels` trait is responsible for capturing the model IDs from Eloquent collections and models prior to serialization, and then restoring them onto the job instance when unserialized, so the entire Eloquent model or collection itself does not need to be serialized in the job instance.

**Comment by jkalousek** [comment]
UpdateMaterials:

```
class UpdateMaterials implements WorkflowableJob
{
    use Dispatchable, InteractsWithQueue, WorkflowStep, SerializesModels;

    protected $MatChunk;

    public function __construct(Collection $MatChunk)
    {
        $this->MatChunk = $MatChunk;
    }


    public function handle(): void
    {
        DB::transaction(function () {
            foreach ($this->MatChunk as $material) {
                try { 

                    $mat = Material::updateOrCreate(
                        [ 'id' => $material->ID ],
                        [
                            ...
                        ]
                    );

                    if(!$mat->wasRecentlyCreated && $mat->wasChanged()){
                        ...
                    }
                    
                    if($mat->wasRecentlyCreated){
                     ...
                    }

                } catch(\Illuminate\Database\QueryException $ex){ 
                    $this->fail();
                }
            }
        });
    }
}
```

**Comment by jkalousek** [comment]
> @jkalousek I'm mainly looking to see if you've included the `SerializesModels` trait onto your `UpdateMaterials` job. If the job does not have this trait, then the entire Eloquent collection of all of your models is serialized, which will definitely exceed the size of the job column.
> 
> The `SerializesModels` trait is responsible for capturing the model IDs from Eloquent collections and models prior to serialization, and then restoring them onto the job instance when unserialized, so the entire Eloquent model or collection itself does not need to be serialized in the job instance.
> 
> Make sure you have this trait added to your queuable jobs. If you already have it, then we can debug from there.

Yes, all of the jobs have 'SerializesModels'

**Comment by stevebauman** [comment]
> EDIT: I'm sorry in this case its not Eloquent model (Illuminate\Database\Eloquent\Collection) just collection (Illuminate\Support\Collection) but I assume it would not make a difference.

This makes a difference -- it must be an Eloquent collection for the collection to be serializable in the job. See the framework implementation:

https://github.com/laravel/framework/blob/10.x/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php

Otherwise, you'll have to send an array of ID's to your job instead, rather than a whole chunk of the DB result. That's too much to serialize.

**Comment by jkalousek** [comment]
> > EDIT: I'm sorry in this case its not Eloquent model (Illuminate\Database\Eloquent\Collection) just collection (Illuminate\Support\Collection) but I assume it would not make a difference.
> 
> This makes a difference -- it must be an Eloquent collection for the collection to be serializable in the job. See the framework implementation:
> 
> https://github.com/laravel/framework/blob/10.x/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php
> 
> Otherwise, you'll have to send an array of ID's to your job instead, rather than a whole chunk of the DB result. That's too much to serialize.

Ok, so If I understand it correctly Eloquent during serialization sends just IDs and than restores data by querying them again from DB and regular collection (Illuminate\Support\Collection) obviously cannot do that so it serializes all the data?
It makes sense I just did not knew the difference. Reason that this particular job does not use Eloquent is that select from the source database is quite complicated and I written it in past in RAW query and didn't see much of a reason to rewrite it into model as its read only.

**Comment by stevebauman** [comment]
> Ok, so If I understand it correctly Eloquent during serialization sends just IDs and than restores data by querying them again from DB and regular collection (Illuminate\Support\Collection) obviously cannot do that so it serializes all the data?

Yup that's correct 👍 

> It makes sense I just did not realized the difference. Reason that this particular job does not use Eloquent is that select from the source database is quite complicated and I written it in past in RAW query and didn't see much of a reason to rewrite it into model as its read only.

I understand. You could always just select the ID's in the initial chunk request and send those IDs into your job to then perform your heavy query in each job.

Going to close this out as either approach should resolve this issue.
